[en]
  title = "Sebastian's Page"
  LanguageName = "English"
  weight = 1

[de]
  title = "Sebastians Seite"
  LanguageName = "Deutsch"
  weight = 2

  # tip: assign the default language the lowest Weight
